apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: customer-api
  name: customer-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-api
  template:
    metadata:
      labels:
        app: customer-api
    spec:
      containers:
        - name: customer-api
          image: jailtonjunior/customer-api:v12
          resources:
            limits:
              cpu: "200m"
              memory: "128Mi"
            requests:
              cpu: "100m"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 120
          env:
            - name: ENVIRONMENT
              value: Production
          ports:
            - containerPort: 8000
