apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: customer-api
  name: customer-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-api
  template:
    metadata:
      labels:
        app: customer-api
    spec:
      containers:
        - name: customer-api
          image: jailtonjunior/customer-api:v31
          resources:
            limits:
              cpu: "200m"
              memory: "128Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 10
            initialDelaySeconds: 120
            failureThreshold: 3
            timeoutSeconds: 60
            successThreshold: 1
          env:
            - name: ENVIRONMENT
              value: Production
          ports:
            - containerPort: 8000
