apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: customer-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: customer-api-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 25
