apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: risk-worker-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: risk-worker-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 25
