name: CI-CD

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  K8S_NAMESPACE: bank
  DOCKER_USERNAME: jailtonjunior

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push (Customer API)
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: customer/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/customer-api:latest
            ${{ env.DOCKER_USERNAME }}/customer-api:v${{ github.run_number }}

      - name: Build and push (Loan API)
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: loan/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/loan-api:latest
            ${{ env.DOCKER_USERNAME }}/loan-api:v${{ github.run_number }}

      - name: Build and push (Risk Worker)
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: risk/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/risk-worker:latest
            ${{ env.DOCKER_USERNAME }}/risk-worker:v${{ github.run_number }}

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: deploy
    steps:
      - uses: actions/checkout@v2

      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}

      - name: Deploy Namespace and Metrics
        uses: Azure/k8s-deploy@v1.3
        with:
          manifests: |
            .k8s/namespaces/bank-ns.yaml
            .k8s/metrics/metric-server

      - name: Deploy MongoDB
        uses: Azure/k8s-deploy@v1.3
        with:
          namespace: ${{ env.K8S_NAMESPACE }}
          manifests: |
            .k8s/deployments/mongo-dp.yaml
            .k8s/services/mongo-svc.yaml

      - name: Deploy RabbitMQ
        uses: Azure/k8s-deploy@v1.3
        with:
          namespace: ${{ env.K8S_NAMESPACE }}
          manifests: |
            .k8s/deployments/rabbit-dp.yaml
            .k8s/services/rabbit-svc.yaml

      - name: Deploy (Customer API)
        uses: Azure/k8s-deploy@v1.3
        with:
          namespace: ${{ env.K8S_NAMESPACE }}
          images: ${{ secrets.env }}/customer-api:v${{ github.run_number }}
          manifests: |
            .k8s/deployments/customer-api-dp.yaml
            .k8s/services/customer-api-svc.yaml
            .k8s/hpas/customer-api-hpa.yaml

      - name: Deploy (Loan API)
        uses: Azure/k8s-deploy@v1.3
        with:
          namespace: ${{ env.K8S_NAMESPACE }}
          images: ${{ secrets.env }}/loan-api:v${{ github.run_number }}
          manifests: |
            .k8s/deployments/loan-api-dp.yaml
            .k8s/services/loan-api-svc.yaml
            .k8s/hpas/loan-api-hpa.yaml

      - name: Deploy (Risk Worker)
        uses: Azure/k8s-deploy@v1.3
        with:
          namespace: ${{ env.K8S_NAMESPACE }}
          images: ${{ secrets.env }}/risk-worker:v${{ github.run_number }}
          manifests: |
            .k8s/deployments/risk-worker-dp.yaml
            .k8s/services/risk-worker-svc.yaml
            .k8s/hpas/risk-worker-hpa.yaml

      - name: Deploy Ingress and Cert-Manager
        uses: Azure/k8s-deploy@v1.3
        with:
          namespace: ${{ env.K8S_NAMESPACE }}
          manifests: |
            .k8s/ingress/bank-ingress.yaml
            .k8s/certmanager/clusterissuer.yml