name: CI-CD

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  K8S_NAMESPACE: bank

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1.9.0
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and push (Customer API)
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: customer/Dockerfile
          push: true
          tags: |
            jailtonjunior/customer-api:latest
            jailtonjunior/customer-api:v${{github.run_number}}

      - name: Build and push (Loan API)
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: loan/Dockerfile
          push: true
          tags: |
            jailtonjunior/loan-api:latest
            jailtonjunior/loan-api:v${{github.run_number}}

      - name: Build and push (Risk Worker)
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: risk/Dockerfile
          push: true
          tags: |
            jailtonjunior/risk-worker:latest
            jailtonjunior/risk-worker:v${{github.run_number}}